### ISSUE TITLE
Wind Turbine Layouts Not Working

### ISSUE THREAD

**Issue by DavidFlanagan22** [MarcusBecker-GitHub/FLORIDyn_Matlab#1]
Hi, I'm a total novice and new to using FLORIDyn.

I got the FLORIDyn app working and running smoothly for the one turbine case.

However when I select another layout from the drop-down menu of the app and try to run it, I get the following error (see screenshot)
![Screenshot from 2022-11-16 11-59-24](https://user-images.githubusercontent.com/101471320/202176439-e0e45e02-f2c7-413e-abf6-ceae5ac8dd27.png)

I would be most grateful if anyone could point me in the right direction.

**Comment by MarcusBecker-GitHub** [comment]
Hey David,

nice to see that you are using the code!

Could you try to do these things:
1. Run one of the examples from Matlab to see if you have access to the function knnsearch:
https://nl.mathworks.com/help/stats/knnsearch.html

2. Given that you have access to the function, can you describe your setup better?
Are you running a specific case? Have you been able to run another case? Did you customize the code?
Maybe I can try to recreate the error.
Also, does this error appear instantly or after the simulation already ran for a bit?

3. If the code throws the error instantly, set a breakpoint in getRelations and have a look what the function is reading
If the code runs fine for a while and then breaks, enclose it into a try catch block and set a breakpoint in the catch section to only read once it breaks.
Something like this:

```
try
	…. knnsearch(____);
catch
	disp(‘breaks’); % Breakpoint here
end
```

**Comment by MarcusBecker-GitHub** [comment]
Closed due to inactivity.
