### ISSUE TITLE
Trouble running mainSOWFA

### ISSUE THREAD

**Issue by hikilinkuja** [MarcusBecker-GitHub/FLORIDyn_Matlab#2]
Hello there!
Today I found the FLORIDyn simulator and got excited to try all the possibilities.
First, I ran the FLORIDyn_App and had no trouble at all with the configurations.
But then mainSOFWA got my interest and, although it has a thorough explanation along the code I found a problem I couldn't solve.
It seems like there's a problem in the **"Running FLORIDyn"** step as you can see in the image below:

![image](https://github.com/MarcusBecker-GitHub/FLORIDyn_Matlab/assets/99562120/1dc1d531-fc38-4dbc-a4bd-e9cd87992023)

If possible, I would appreciate any help or advice anyone can give.

Thanks a lot!

**Comment by MarcusBecker-GitHub** [comment]
Hey,

can you share the input that you are using?
Maybe I can recreate it.
It seems like the variable "i" does not behave as expected - could you set a breakpoint in getWindVec4 - Line 55 and show what the workspace looks like?

Cheers!

**Comment by hikilinkuja** [comment]
Hi again!

Thanks for the quick response.
I removed the input commentary for a better read.
I changed Running FLORIDyn to:
```
[powerHist,OP,T,UF] = ...
    FLORIDyn('/ValidationData/csv/_2T_20_rotorSpeedFiltered.csv', '/ValidationData/csv/_2T_20_generatorPower.csv', '/ValidationData/csv/_2T_20_nacelleYaw.csv', '/ValidationData/csv/2T_20_bladePitch.csv');
```
Now the errors are different:

![image](https://github.com/MarcusBecker-GitHub/FLORIDyn_Matlab/assets/99562120/f0fa6e23-e75c-41ca-a92b-f5c91341db62)


Here is the input:

```
main_addPaths;

%% Set controller type


Control.Type = 'SOWFA_greedy_yaw';
Control.init = true;

%% Set path to SOWFA files


file2val = '/ValidationData/csv/_2T_20_nacelleYaw.csv';
file2val = '/ValidationData/csv/_2T_20_rotorSpeedFiltered.csv';
file2val = '/ValidationData/csv/2T_20_bladePitch.csv';
file2val = '/ValidationData/csv/2T_20_generatorPower.csv';

%% Load Layout

[T,fieldLims,Pow,VCpCt,chain] = loadLayout('twoDTU10MW');

%% Load the environment

[U, I, UF, Sim] = loadWindField('const',... 
    'windAngle',0,...
    'SimDuration',1000,...
    'FreeSpeed',true,...
    'Interaction',true,...
    'posMeasFactor',2000,...
    'alpha_z',0.1,...
    'windSpeed',8,...
    'ambTurbulence',0.06);

%% Visulization

Vis.online      = true;
Vis.Snapshots   = false;
Vis.FlowField   = false;
Vis.PowerOutput = true;
Vis.Console     = true;

%% Create starting OPs and build opList

[OP, chain] = assembleOPList(chain,T,'sunflower');

%% Running FLORIDyn
[powerHist,OP,T,UF] = ...
    FLORIDyn('/ValidationData/csv/_2T_20_rotorSpeedFiltered.csv', '/ValidationData/csv/_2T_20_generatorPower.csv', '/ValidationData/csv/_2T_20_nacelleYaw.csv', '/ValidationData/csv/2T_20_bladePitch.csv');

%% Compare power plot
if Vis.PowerOutput
    % Plotting
    f = figure;
    hold on
    nT = length(T.D);
    % Get SOWFA data if avaiable
    if exist([file2val 'nacelleYaw.csv'], 'file') == 2
        powSOWFA_WPS = importGenPowerFile([file2val 'generatorPower.csv']);
        labels = cell(2*nT,1);
        % =========== SOWFA data ===========
        for iT = 1:nT
            plot(...
                powSOWFA_WPS(iT:nT:end,2)-powSOWFA_WPS(iT,2),...
                powSOWFA_WPS(iT:nT:end,3)/UF.airDen,...
                '-.','LineWidth',1)
            labels{iT} = ['T' num2str(iT-1) ' SOWFA wps'];
        end
    else
        labels = cell(nT,1);
    end
    
    % ========== FLORIDyn data =========
    for iT = 1:length(T.D)
        plot(powerHist(:,1),powerHist(:,iT+1),'LineWidth',1.5)
        labels{end-nT+iT} = ['T' num2str(iT-1) ' FLORIDyn'];
    end
    
    hold off
    grid on
    xlim([0 powerHist(end,1)])
    xlabel('Time [s]')
    ylabel('Power generated [W]')
    title([num2str(nT) ' turbine case, based on SOWFA data'])
    legend(labels)
    % ==== Prep for export ==== %
    % scaling
    f.Units               = 'centimeters';
    f.Position(3)         = 16.1; % A4 line width
    set(gca,'LooseInset', max(get(gca,'TightInset'), 0.04))
    f.PaperPositionMode   = 'auto';
end
```

**Comment by MarcusBecker-GitHub** [comment]
The change to the way you call the FLORIDyn function won't work, since you are passing new arguments that don't fit the code.
So this function call needs to be the same:
```
[powerHist,OP,T,chain]=...
    FLORIDyn(T,OP,U,I,UF,Sim,fieldLims,Pow,VCpCt,chain,Vis,Control);
```

Are you running one of the example SOWFA cases or do you try to replicate a SOWFA simulation you ran yourself?

**Comment by hikilinkuja** [comment]
Oh, I thought that line was the problem.
If I revert to the state before changing that same line I get this:

```
main_addPaths;

%% Set controller type

Control.Type = 'SOWFA_greedy_yaw';
Control.init = true;

%% Set path to SOWFA files

file2val = '/ValidationData/csv/2T_20_nacelleYaw.csv';
file2val = '/ValidationData/csv/2T_20_rotorSpeedFiltered.csv';
file2val = '/ValidationData/csv/2T_20_bladePitch.csv';
file2val = '/ValidationData/csv/2T_20_generatorPower.csv';

%% Load Layout

[T,fieldLims,Pow,VCpCt,chain] = loadLayout('twoDTU10MW');

%% Load the environment

[U, I, UF, Sim] = loadWindField('const',... 
    'windAngle',0,...
    'SimDuration',1000,...
    'FreeSpeed',true,...
    'Interaction',true,...
    'posMeasFactor',2000,...
    'alpha_z',0.1,...
    'windSpeed',8,...
    'ambTurbulence',0.06);

%% Visulization

Vis.online      = true;
Vis.Snapshots   = false;
Vis.FlowField   = false;
Vis.PowerOutput = true;
Vis.Console     = true;

%% Create starting OPs and build opList

[OP, chain] = assembleOPList(chain,T,'sunflower');

%% Running FLORIDyn

[powerHist,OP,T,chain]=...
    FLORIDyn(T,OP,U,I,UF,Sim,fieldLims,Pow,VCpCt,chain,Vis,Control);

%% Compare power plot

if Vis.PowerOutput
    % Plotting
    f = figure;
    hold on
    nT = length(T.D);
    % Get SOWFA data if avaiable
    if exist([file2val 'nacelleYaw.csv'], 'file') == 2
        powSOWFA_WPS = importGenPowerFile([file2val 'generatorPower.csv']);
        labels = cell(2*nT,1);

        % =========== SOWFA data ===========
        for iT = 1:nT
            plot(...
                powSOWFA_WPS(iT:nT:end,2)-powSOWFA_WPS(iT,2),...
                powSOWFA_WPS(iT:nT:end,3)/UF.airDen,...
                '-.','LineWidth',1)
            labels{iT} = ['T' num2str(iT-1) ' SOWFA wps'];
        end
    else
        labels = cell(nT,1);
    end
    
    % ========== FLORIDyn data =========
    for iT = 1:length(T.D)
        plot(powerHist(:,1),powerHist(:,iT+1),'LineWidth',1.5)
        labels{end-nT+iT} = ['T' num2str(iT-1) ' FLORIDyn'];
    end
    
    hold off
    grid on
    xlim([0 powerHist(end,1)])
    xlabel('Time [s]')
    ylabel('Power generated [W]')
    title([num2str(nT) ' turbine case, based on SOWFA data'])
    legend(labels)
    % ==== Prep for export ==== %
    % scaling
    f.Units               = 'centimeters';
    f.Position(3)         = 16.1; % A4 line width
    set(gca,'LooseInset', max(get(gca,'TightInset'), 0.04))
    f.PaperPositionMode   = 'auto';
end
```

And the error:

![image](https://github.com/MarcusBecker-GitHub/FLORIDyn_Matlab/assets/99562120/a8d3c54f-f9e6-4788-94d8-df8ea5a9b02c)

**Comment by hikilinkuja** [comment]
Hi @MarcusBecker-GitHub, hope you had a great weekend!

Forgot to mention that I was running one of the example SOWFA cases.

Thanks!

**Comment by MarcusBecker-GitHub** [comment]
Hi, try replacing
`file2val = '/ValidationData/csv/2T_20_nacelleYaw.csv';`
`file2val = '/ValidationData/csv/2T_20_rotorSpeedFiltered.csv';`
`file2val = '/ValidationData/csv/2T_20_bladePitch.csv';`
`file2val = '/ValidationData/csv/2T_20_generatorPower.csv';`
with only 
`file2val = '/ValidationData/csv/_2T_20_';` < Typo, should be /ValidationData/csv/2T_20_

The code will add the endings, such as "nacelleYaw.csv" by itself internally.

**Comment by hikilinkuja** [comment]
Strange... I just tried that but the error is exactly the same as the print screen I posted.

**Comment by MarcusBecker-GitHub** [comment]
Ah, you are missing the
`LoadSOWFAData;`
script call - if you look in the repo version of the [function](https://github.com/MarcusBecker-GitHub/FLORIDyn_Matlab/blob/main/mainSOWFA.m), we first set the file name and then read the data from the SOWFA files (Line 52 and 53).

So it should be
`file2val = '/ValidationData/csv/2T_20_';`
`LoadSOWFAData;`

Mind the typo I had before in the simulation name.

**Comment by hikilinkuja** [comment]
You are totally right, somewhere along the way I lost that information.
I also changed the typo.

Unfortunately, I'm still getting two errors:

![image](https://github.com/MarcusBecker-GitHub/FLORIDyn_Matlab/assets/99562120/9d674b74-5b84-4261-9c25-7aefae5f2c80)

**Comment by MarcusBecker-GitHub** [comment]
That seems to be indeed a bug that slipped through!
Line 5 in LoadSOWFAData.m is
`Control.yawSOWFA(:,2) = yawSOWFA(:,2)-yawSOWFA(1,2);`
and should be
`Control.yawSOWFA(:,2) = Control.yawSOWFA(:,2)-Control.yawSOWFA(1,2);`

I changed the line and merged the fix. For me the code now runs as expected.
Could you confirm on your side? Then I'd close this issue.

**Comment by hikilinkuja** [comment]
Hi @MarcusBecker-GitHub. It totally worked!
I just had to remove the "end" in the last line of the code for it to work.
Thank you so much for your help!

**Comment by Xianlucky** [comment]
Hello, Professor!
Today I discovered the FLORIDyn simulator and was excited to try out the possibilities.
First, I ran FLORIDyn_App and did not encounter any problems with the configuration.
Then, mainSOFWA piqued my interest, and despite its thorough explanation of the code, I found an unsolvable problem.
As you can see below, there seems to be a problem at the “Run FLORIDyn” step:
![2024 08 30](https://github.com/user-attachments/assets/4adec97e-9040-495f-b8c7-bf669e282d66)
I got the above error by changing just one line of code, which was changed as follows:
        file2val = '/ValidationData/csv/3T_00_';
        
![image](https://github.com/user-attachments/assets/e470a95f-46b6-4fae-ac51-4155bd89218d)
